# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='web',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Nicolle Knust'), (1, 'Wunder Woman')], default=0, null=True, verbose_name='web'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
