# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170223_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='web',
        ),
    ]
