# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20170513_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=b'services/images/3abd1471/', verbose_name='image'),
        ),
    ]
