# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('image', models.ImageField(upload_to=b'services/images/a4ac5a05/', verbose_name='image')),
                ('description', models.TextField(blank=True, editable=False, null=True, verbose_name='descripci\xf3n')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='edition date', null=True)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripci\xf3n')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='image',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='programs.Program', verbose_name='program'),
        ),
    ]
